version: "3.8"

services:

  server:
    build: ./hospital_node      
    working_dir: /app
    volumes:
      - ./server:/app
      - ./fhe_keys_data:/keys
    command: ["python", "server.py"]
    ports:
      - "9090:8080"
    networks:
      - fl_network

  hospital_1:
    build: ./hospital_node
    working_dir: /app
    environment:
      - SERVER_ADDRESS=server:8080
      - CLIENT_ID=0
      - NUM_CLIENTS=3
      - PARTITION_MODE=dirichlet
      - DIRICHLET_ALPHA=0.5
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./hospital_node:/app
      - ./metricas_locais:/app/metricas_locais
      - mnist_data:/data
      - ./fhe_keys_data:/keys
      - ~/.aws:/root/.aws:ro
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    depends_on:
      - server
    command: ["python", "client.py"]
    networks:
      - fl_network

  hospital_2:
    build: ./hospital_node
    working_dir: /app
    environment:
      - SERVER_ADDRESS=server:8080
      - CLIENT_ID=1
      - NUM_CLIENTS=3
      - PARTITION_MODE=dirichlet
      - DIRICHLET_ALPHA=0.5
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./hospital_node:/app
      - ./metricas_locais:/app/metricas_locais
      - mnist_data:/data
      - ./fhe_keys_data:/keys
      - ~/.aws:/root/.aws:ro
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    depends_on:
      - server
    command: ["python", "client.py"]
    networks:
      - fl_network

  hospital_3:
    build: ./hospital_node
    working_dir: /app
    environment:
      - SERVER_ADDRESS=server:8080
      - CLIENT_ID=2
      - NUM_CLIENTS=3
      - PARTITION_MODE=dirichlet
      - DIRICHLET_ALPHA=0.5
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./hospital_node:/app
      - ./metricas_locais:/app/metricas_locais
      - mnist_data:/data
      - ./fhe_keys_data:/keys
      - ~/.aws:/root/.aws:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    depends_on:
      - server
    command: ["python", "client.py"]
    networks:
      - fl_network

networks:
  fl_network:

volumes:
  mnist_data: